name: Nost Unit Tests
run-name: Run Nost Unit Tests
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install project dependencies
        run: |
          echo "Installing project dependencies..."
          cargo build

      - name: Start CI
        run: |
          echo "Starting CI..."
          cargo test
